chore(codebase): upgrade to react-native 0.73.6 and remove all dependencies

diff --git a/ProjectName/scripts/clean b/ProjectName/scripts/clean
--- a/ProjectName/scripts/clean
+++ b/ProjectName/scripts/clean
@@ -1,13 +1,36 @@
 #!/bin/bash
+export CLEAN_HARD=0
+export KEEP_ENVIRONMENT=0
+#
+# Parse options
+while (( "$#" )); do
+  case "$1" in
+    --hard)
+      CLEAN_HARD=1
+      shift
+      ;;
+    --keep-env)
+      KEEP_ENVIRONMENT=1
+      shift
+      ;;
+    --*)
+      echo "Option: $1"
+      shift 2
+      ;;
+    *)
+      echo "Invalid option: $1" 1>&2
+      exit 1
+      ;;
+  esac
+done
 # Task 5: hard clean: remove .lock file if it exists that trigger by --hard flag as boolean
-if [ "$1" = "--hard" ]; then
+if [ "$CLEAN_HARD" = "1" ]; then
   echo "Running hard clean..."
   rm package-lock.json
   rm yarn.lock
   rm ios/Podfile.lock
   # remove gem lock
   rm Gemfile.lock
-  echo "Task 3 completed."
 else
   echo "Skipping hard clean as it is only required for --hard flag."
 fi
@@ -16,7 +39,6 @@ fi
 echo "Running clean android..."
 cd android && ./gradlew clean
 cd ..
-echo "Task 4 completed."
 
 # Task: remove android .gradle
 echo "Running remove android .gradle..."
@@ -34,7 +56,7 @@ echo "Task 5 completed."
 # Task 2: run pod deintegrate for react-native
 if [[ "$OSTYPE" == "darwin"* ]]; then
   echo "Running pod deintegrate..."
-  cd ios && pod deintegrate && cd ..
+  cd ios && rm -rf Pods && cd ..
   rm -rf ios/build
   echo "Task 2 completed."
 else
@@ -44,9 +66,14 @@ fi
 # Task 1: run remove node_modules folder
 echo "Running remove node_modules folder..."
 rm -rf node_modules
-rm -rf vendor
 rm -rf $TMPDIR/react-*
-echo "Task 1 completed."
+
+if [ "$KEEP_ENVIRONMENT" = "0" ]; then
+  echo "Running remove bundle vendor..."
+  rm -rf vendor
+else
+  echo "Skipping remove bundle as it is only required for --keep-env flag."
+fi
 
 # Task: clean jest cache
 echo "Running clean jest cache..."
